#!/bin/sh

if test "$1" = "-h" || test "$1" = "--help"
then
    echo "record Sound"
    echo "run $0 [param oggenc]"
    exit
fi

date=`date +%Y%m%d-%H:%m:%S`

parec    --channels 2 --rate 44100 --format s16le | \
    oggenc --raw -C 2     -R 44100       -B 16 \
    $@ \
    - -o $date.ogg
